# Generated by Django 5.1.3 on 2024-11-12 00:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materiales', models.CharField(max_length=255)),
                ('cantidad', models.IntegerField()),
                ('codigo_barras', models.CharField(blank=True, max_length=12, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'db_table': 'material',
            },
        ),
        migrations.CreateModel(
            name='ActualizacionInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('codigo_barras', models.CharField(blank=True, max_length=100, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.material')),
            ],
            options={
                'verbose_name': 'Actualización de Inventario',
                'verbose_name_plural': 'Actualizaciones de Inventario',
                'db_table': 'actualizacion_inventario',
            },
        ),
    ]
