# Generated by Django 5.1.3 on 2024-12-10 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pruebas',
        ),
    ]
