# Generated by Django 5.1.3 on 2024-12-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pruebas', '0004_delete_pruebas'),
    ]

    operations = [
        migrations.CreateModel(
            name='pruebas',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamano', models.BooleanField(null=False)),
                ('color', models.BooleanField(null=False)),
                ('relleno', models.BooleanField(null=False)),
            ],
            options={
                'verbose_name': 'pruebas',
                'verbose_name_plural': 'pruebas',
                'db_table': 'pruebas',
            },
        ),
    ]
