# Generated by Django 5.1.3 on 2024-11-08 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('trackNumber', models.CharField(max_length=10)),
                ('clientName', models.CharField(max_length=50)),
                ('procesado', models.BooleanField(null=True)),
                ('armado', models.BooleanField(null=True)),
                ('prueba', models.BooleanField(null=True)),
                ('etiquetado', models.BooleanField(null=True)),
                ('enviado', models.BooleanField(null=True)),
            ],
            options={
                'verbose_name': 'Tracking',
                'verbose_name_plural': 'Trackings',
                'db_table': 'tracking',
                'ordering': ['id'],
            },
        ),
    ]
