# Generated by Django 5.1.3 on 2024-11-12 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_alter_tracking_id_alter_tracking_tracknumber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tracking',
            options={'ordering': ['trackNumber'], 'verbose_name': 'Tracking', 'verbose_name_plural': 'Trackings'},
        ),
        migrations.RemoveField(
            model_name='tracking',
            name='id',
        ),
        migrations.AlterField(
            model_name='tracking',
            name='trackNumber',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
