# Generated by Django 5.1.3 on 2024-11-12 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_alter_tracking_options_remove_tracking_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='armado',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='enviado',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='etiquetado',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='procesado',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='prueba',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
