# Generated by Django 5.1.3 on 2024-11-12 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_alter_tracking_armado_alter_tracking_enviado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='armado',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='enviado',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='etiquetado',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='procesado',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='prueba',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
